<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="9" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="262141" started-at="2017-08-15T13:12:44Z" finished-at="2017-08-15T13:17:06Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="262141" started-at="2017-08-15T13:12:44Z" finished-at="2017-08-15T13:17:06Z">
      <class name="test.GoThroughHotSortTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:test.GoThroughHotSortTest@2ef9b8bc]" name="setUp" is-config="true" duration-ms="5876" started-at="2017-08-15T21:14:54Z" finished-at="2017-08-15T21:15:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="goThroughHotSortTest()[pri:0, instance:test.GoThroughHotSortTest@2ef9b8bc]" name="goThroughHotSortTest" duration-ms="12702" started-at="2017-08-15T21:15:00Z" finished-at="2017-08-15T21:15:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [全球原生] but found [HOT]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [全球原生] but found [HOT]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at test.GoThroughHotSortTest.goThroughHotSortTest(GoThroughHotSortTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goThroughHotSortTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.GoThroughHotSortTest@2ef9b8bc]" name="tearDown" is-config="true" duration-ms="1709" started-at="2017-08-15T21:15:13Z" finished-at="2017-08-15T21:15:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.GoThroughHotSortTest -->
      <class name="test.GoInService">
        <test-method status="PASS" signature="setUp()[pri:0, instance:test.GoInService@1e67b872]" name="setUp" is-config="true" duration-ms="5917" started-at="2017-08-15T21:15:48Z" finished-at="2017-08-15T21:15:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="goService()[pri:0, instance:test.GoInService@1e67b872]" name="goService" duration-ms="35952" started-at="2017-08-15T21:15:54Z" finished-at="2017-08-15T21:16:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goService -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.GoInService@1e67b872]" name="tearDown" is-config="true" duration-ms="3026" started-at="2017-08-15T21:16:30Z" finished-at="2017-08-15T21:16:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.GoInService -->
      <class name="test.GoThroughGirlClothSortTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:test.GoThroughGirlClothSortTest@5315b42e]" name="setUp" is-config="true" duration-ms="5990" started-at="2017-08-15T21:14:35Z" finished-at="2017-08-15T21:14:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="goThroughGirlClothTest()[pri:0, instance:test.GoThroughGirlClothSortTest@5315b42e]" name="goThroughGirlClothTest" duration-ms="11772" started-at="2017-08-15T21:14:41Z" finished-at="2017-08-15T21:14:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [创意生活] but found [女装]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [创意生活] but found [女装]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at test.GoThroughGirlClothSortTest.goThroughGirlClothTest(GoThroughGirlClothSortTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goThroughGirlClothTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.GoThroughGirlClothSortTest@5315b42e]" name="tearDown" is-config="true" duration-ms="1840" started-at="2017-08-15T21:14:53Z" finished-at="2017-08-15T21:14:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.GoThroughGirlClothSortTest -->
      <class name="test.EnterEndGoodPage">
        <test-method status="PASS" signature="setUp()[pri:0, instance:test.EnterEndGoodPage@60addb54]" name="setUp" is-config="true" duration-ms="6619" started-at="2017-08-15T21:16:33Z" finished-at="2017-08-15T21:16:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="goGoodPage()[pri:0, instance:test.EnterEndGoodPage@60addb54]" name="goGoodPage" duration-ms="25201" started-at="2017-08-15T21:16:39Z" finished-at="2017-08-15T21:17:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goGoodPage -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.EnterEndGoodPage@60addb54]" name="tearDown" is-config="true" duration-ms="1839" started-at="2017-08-15T21:17:04Z" finished-at="2017-08-15T21:17:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.EnterEndGoodPage -->
      <class name="test.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:test.LoginTest@2c6a3f77]" name="setUp" is-config="true" duration-ms="6305" started-at="2017-08-15T21:13:10Z" finished-at="2017-08-15T21:13:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginTest(java.lang.String, java.lang.String)[pri:0, instance:test.LoginTest@2c6a3f77]" name="loginTest" duration-ms="38814" started-at="2017-08-15T21:13:16Z" description="测试账号登录" data-provider="LoginSucess" finished-at="2017-08-15T21:13:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[18601942313]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456a]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.LoginTest@2c6a3f77]" name="tearDown" is-config="true" duration-ms="1534" started-at="2017-08-15T21:13:55Z" finished-at="2017-08-15T21:13:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.LoginTest -->
      <class name="test.GoThroughPresentSortTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:test.GoThroughPresentSortTest@62043840]" name="setUp" is-config="true" duration-ms="5895" started-at="2017-08-15T21:14:15Z" finished-at="2017-08-15T21:14:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="goThroughPresentTest()[pri:0, instance:test.GoThroughPresentSortTest@62043840]" name="goThroughPresentTest" duration-ms="12263" started-at="2017-08-15T21:14:21Z" finished-at="2017-08-15T21:14:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [有机美妆] but found [礼物]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [有机美妆] but found [礼物]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at test.GoThroughPresentSortTest.goThroughPresentTest(GoThroughPresentSortTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goThroughPresentTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.GoThroughPresentSortTest@62043840]" name="tearDown" is-config="true" duration-ms="1600" started-at="2017-08-15T21:14:33Z" finished-at="2017-08-15T21:14:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.GoThroughPresentSortTest -->
      <class name="test.GoThroughPeishiSortTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:test.GoThroughPeishiSortTest@246ae04d]" name="setUp" is-config="true" duration-ms="5770" started-at="2017-08-15T21:13:57Z" finished-at="2017-08-15T21:14:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="goThroughPeishiTest()[pri:0, instance:test.GoThroughPeishiSortTest@246ae04d]" name="goThroughPeishiTest" duration-ms="10629" started-at="2017-08-15T21:14:02Z" finished-at="2017-08-15T21:14:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [有机食品] but found [配饰]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [有机食品] but found [配饰]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at test.GoThroughPeishiSortTest.goThroughPeishiTest(GoThroughPeishiSortTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goThroughPeishiTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.GoThroughPeishiSortTest@246ae04d]" name="tearDown" is-config="true" duration-ms="2200" started-at="2017-08-15T21:14:13Z" finished-at="2017-08-15T21:14:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.GoThroughPeishiSortTest -->
      <class name="test.LogoutTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:test.LogoutTest@1324409e]" name="setUp" is-config="true" duration-ms="8001" started-at="2017-08-15T21:12:44Z" finished-at="2017-08-15T21:12:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="logoutTest(java.lang.String, java.lang.String)[pri:0, instance:test.LogoutTest@1324409e]" name="logoutTest" duration-ms="16224" started-at="2017-08-15T21:12:52Z" description="测试账号登录" data-provider="LoginSucess" finished-at="2017-08-15T21:13:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[18601942313]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456a]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.LogoutTest@1324409e]" name="tearDown" is-config="true" duration-ms="1530" started-at="2017-08-15T21:13:08Z" finished-at="2017-08-15T21:13:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.LogoutTest -->
      <class name="test.GoThroughMainPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:test.GoThroughMainPageTest@5d624da6]" name="setUp" is-config="true" duration-ms="5973" started-at="2017-08-15T21:15:15Z" finished-at="2017-08-15T21:15:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="goThroughMainPageTest()[pri:0, instance:test.GoThroughMainPageTest@5d624da6]" name="goThroughMainPageTest" duration-ms="24928" started-at="2017-08-15T21:15:21Z" finished-at="2017-08-15T21:15:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at test.GoThroughMainPageTest.goThroughMainPageTest(GoThroughMainPageTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goThroughMainPageTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.GoThroughMainPageTest@5d624da6]" name="tearDown" is-config="true" duration-ms="1968" started-at="2017-08-15T21:15:46Z" finished-at="2017-08-15T21:15:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.GoThroughMainPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
